source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MRLCircleChart_Example' do
  pod 'MRLCircleChart', path: '../'
end

target 'MRLCircleChart_Tests' do
  pod 'MRLCircleChart', path: '../'
  pod 'FBSnapshotTestCase', git: 'https://github.com/facebook/ios-snapshot-test-case.git', branch: 'master'
  pod 'Quick', '0.10.0'
  pod 'Nimble', '5.0.0'
  pod 'Nimble-Snapshots', '4.2.0'
end

post_install do |installer|
  configure_spacing(installer, '2')
  installer.pods_project.targets.each do |target|
    setup_swift_version(target, 3.0)
  end
end

def setup_swift_version(target, version)
  target.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] ||= version
  end
end

def configure_spacing(installer, spacing)
  puts(" >> Sets indent_width and tab_width to `#{spacing}` for Pods project")
  main_group = installer.pods_project.root_object.main_group
  main_group.indent_width = spacing
  main_group.tab_width = spacing
end
